cd .\samples\chlang\voting\
cd .\01_basic_voting\
..\..\..\..\soccer .\basic_voting.chosoc
cd ..
cd .\02_comments\
..\..\..\..\soccer .\comments.chosoc
cd ..
cd .\03_condorcet\
..\..\..\..\soccer .\condorcet.chosoc
cd ..
cd .\04_condorcet_paradox\
..\..\..\..\soccer .\paradox.chosoc
cd ..
cd .\05_borda\
..\..\..\..\soccer .\borda.chosoc
cd ..\..\..\..\